### ISSUE TITLE
How to compute the color value?

### ISSUE THREAD

**Issue by nuintun** [netzkolchose/node-ansiterminal#1]
Hello, I want to use ansiterminal create html string, but i don't know how to compute the color value. Can you write one, thanks~

**Comment by nuintun** [comment]
Thanks, I have found it in jquery.browserterminal.js~

**Comment by jerch** [comment]
Yes the jquery plugin does the html conversions. Also `TChar.getAttributes()` in ansiterminal.js might give you a more readable idea how to get values from the bit fields.
Please be aware that both the terminal and the frontend end output with jquery.browserterminal is still early alpha. Double width characters cause me headaches, the handling of those is still messy esp. at the end of a terminal line.
